; This file is read from the same directory as NteModManager.exe.
; Restart the application after changing a value.

[Paths]
mods_directory=E:/Neverness To Everness/Client/WindowsNoEditor/HT/Content/Paks/~mods
backups_directory=E:/Neverness To Everness/Mods/Backups
background_images_directory=F:/pictures/真人
game_launcher=E:/Neverness To Everness/NTELauncher.exe
packager_directory=E:/Neverness To Everness/Mods/ModManager/傻瓜打包器

[Categories]
names=安魂曲, 薄荷, 达芙蒂尔, 法帝娅, 九原, 娜娜莉, 主角, 小吱, 浔, 伊洛伊, 早雾, 真红, 哈尼娅, 哈索尔, 海月

[Preferences]
mod_list_sort_order=1
mod_category_order=真红, 安魂曲, 娜娜莉, 伊洛伊, 小吱, 薄荷, 九原, 达芙蒂尔, 哈尼娅, 法帝娅, 哈索尔, 主角, 海月, 浔, 早雾